name: "Paola Solorzano Bravo"
repo_names:
  - ATLAS-iOS-Fall-22-Personal-Project
  
10-ux-ui-criticism:  
  - https://vimeo.com/755667691
  - https://vimeo.com/755671736
  
11-models-from-data:
  - https://github.com/Paola-Solorzano/ATLAS-iOS-Fall-22-Personal-Project/blob/main/App/StoryModels.swift#L7
